default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: gamble_kakeibo2_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: gamble_kakeibo2_test

production:
  <<: *default
  database: gamble_kakeibo2_production
  username: gamble_kakeibo2
  password: <%= ENV["GAMBLE_KAKEIBO2_DATABASE_PASSWORD"] %>
